### PR TITLE
Replace BackAndroid by BackHandler, fix flashing menu for Android Platform

### PR DESCRIPTION
**Pull request by amensouissi**

### CODE REVIEW

**Comment by jqn** [comment]
It would be great to have this merged it is causing problem with this awesome library.

**Comment by trickeyd** [comment]
Good changes, but surely you cant force your auto-formatting on someone else's code...

**Comment by fabriziomoscon** [comment]
I have also this problem since I am using RN 0.46

this PR contains also changes regarding animation:
```
scaleAnim: new Animated.Value(Platform.OS === "android" ? 0.01 : 0.001)
```

I think that code comparisons for both the maintainer and anyone reading these changes should not include code style and formatting. Doing so makes it very difficult to understand what really changed versus style replacement.

Please consider keeping the original repo's code styles and moving the animation change into another PR.

**Comment by amensouissi** [comment]
Hello,
Please see #59 and #60

**Comment by fabriziomoscon** [comment]
very good. This can be closed now

**Pull request closed without merging**
